version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
           - build
           - test
          parameters:
            api-key:
              default: HEROKU_API_KEY
              description: The name of the environment variable containing your Heroku API Key.
              type: env_var_name
            app-name:
              default: $HEROKU_APP_NAME
              type: string
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: gradle:alpine
    steps:
      - checkout
      - run: ./gradlew bootJar
      - persist_to_workspace:
          root: ./
          paths:
            - build/
            - .gradle/

  test:
    docker:
      - image: gradle:alpine
    steps:
      - checkout
      - run: ./gradlew test
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results