version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      #- test
      - deploy:
          requires:
            - build
            - test




      #- heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
         # post-steps:
           # - run:
            #   name : Run Application
             #  command: java -Xmx512m -Xms256m -jar demo-0.0.1-SNAPSHOT.jar
          #requires:
           #- build
          #filters:
           # branches:
            #  only: master


jobs:
  build:
    docker:
      - image: gradle:alpine
    steps:
      - checkout
      - run: ./gradlew bootJar
      - persist_to_workspace:
          root: ./
          paths:
            - build/
            - .gradle/

  test:
    docker:
      - image: gradle:alpine
    steps:
      - checkout
      - run: ./gradlew test
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results

  deploy:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - heroku/deploy-via-git
          #filters:
           #   branches:
            #    only: master
      - run:
          name: Run Application
          command: java -Xmx512m -Xms256m -jar demo-0.0.1-SNAPSHOT.jar